collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#3C2E05'
    - '#C8C8C8'
    - '#7D7D7D'
  rhythmicContrast: 0
typography_spectrum: 0.390681
layout_spectrum: 0.327957
name: sherrikauk
